name: Doctrine
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    uses: szl-holdings/.github/.github/workflows/doctrine-check.yml@e243d95d969698afb7943b58e8f148b41d8b38e3 # .github PR #197
