name: Doctrine
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    uses: szl-holdings/.github/.github/workflows/doctrine-check.yml@52c3d54c091996a7cece94af8b8446f6996c6f83 # .github PR #202
