name: Doctrine
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    uses: szl-holdings/.github/.github/workflows/doctrine-check.yml@36ade347cb642acb74e11a27eeabe3c53de17f45 # .github PR #197
